src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

use phpDocumentor\Reflection\Types\Integer;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @Vich\Uploadable
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(message = "Email '{{ value }}' n'est pas un email valide."  )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * * @Assert\Regex(
     * pattern = "/^[a-z A-Z]+$/i",
     * htmlPattern = "^[a-z A-Z]+$",
     * message=" first name ne doit contenir que  des alaphaptique"
     * )
     * @Assert\NotBlank
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * * @Assert\Regex(
     * pattern = "/^[a-z A-Z]+$/i",
     * htmlPattern = "^[a-z A-Z]+$",
     * message=" first name ne doit contenir que  des alaphaptique"
     * )
     * @Assert\NotBlank
     */
    private $lastName;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private $pins;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="user")
     */
    private $contacts;



    public function __construct()
    {
        $this->pins = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->contacts = new ArrayCollection();

       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection|Pin[]
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }

    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->removeElement($pin)) {
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }
    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
    public function getGravatarUrl(?int $size = 100)
    {
        return sprintf('https://www.gravatar.com/avatar/%s?s=%d', md5(strtolower(trim($this->getEmail()))), $size);
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setUser($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getUser() === $this) {
                $contact->setUser(null);
            }
        }

        return $this;
    }
    public function addRoles(string $roles): self
    {
        if (!in_array($roles, $this->roles)) {
            $this->roles[] = $roles;
        }

        return $this;
    }


   
}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Pin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('audience', ChoiceType::class, [
                'choices'  => [
                    'Public' => 'Public',
                    'Privée' => 'Privée',

                ],
            ])
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image (JPG or PNG file)',
                'required' => false,

                'allow_delete' => true,
                'download_label' => 'Télécharger',
                'download_uri' => true,



            ])
            ->add('title', TextType::class)
            ->add('categorie', ChoiceType::class, [
                'choices'  => [
                    'choose'=>'',
                    'Love' => 'Love',
                    'Nature' => 'Nature',
                    'Sport'=>'Sport',
                    "Birthday"=>"Birthday",
                    "Food"=>"Food",
                    "Other"=>"Other"

                ],
            ])
            ->add('description', TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pin::class,
        ]);
    }
}

src/Controller/PinController.php
<?php

namespace App\Controller;

use App\Entity\Comments;
use App\Entity\Pin;
use App\Form\PinType;
use App\Repository\CommentsRepository;
use App\Repository\PinRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use SebastianBergmann\CodeCoverage\Report\Text;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Validator\Constraints\Length;

class PinController extends AbstractController
{
    /**
     * @Route("/", name="app_home")
     *
     */
    public function index1(PinRepository $pinRepository): Response
    {
        $pins = $pinRepository->findBy(['audience'=>'Public'], ['createdAt' => 'DESC']);

        return $this->render('pin/home.html.twig', [
            'pins'=>$pins,

        ]);
    }

    /**
     * @Route("/mypins", name="app_mypin")
     *
     */
    public function mypin(PinRepository $pinRepository): Response
    {
        $pins = $pinRepository->findBy(['user'=>$this->getUser()], ['createdAt' => 'DESC']);

        return $this->render('pin/my_pins.html.twig', [
            'pins'=>$pins,

        ]);
    }



    /**
     * @Route("/pin/{id<[0-9]+>}", name="app_pin_show", methods="GET")
     *
     *
     */
    public function show(Pin $pin): Response
    {

        return $this->render('pin/show.html.twig', compact('pin'));
    }

    /**
     * @Route("/pin/create", name="app_pin_create",methods={"GET", "POST"})
     *@Security("is_granted('ROLE_USER') and user.isVerified()", statusCode=404, message="you're not allowed , please check your account mail")
     */
    public function create(Request $request, EntityManagerInterface $em, UserRepository $userRepo):Response{

            $pin = new Pin;

            $form = $this->createForm(PinType::class, $pin);

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $pin->setUser($this->getUser());
                $em->persist($pin);
                $em->flush();

                $this->addFlash('success', 'Pin successfully created!');

                return $this->redirectToRoute('app_home');
            }

            return $this->render('pin/create.html.twig', [
                'form' => $form->createView()
            ]);
        }

    /**
     * @Route("/pin/{id<[0-9]+>}/edit", name="app_pin_edit", methods={"GET", "POST"})
     *@Security("is_granted('ROLE_USER') and pin.getUser()==user", statusCode=404, message="you're not allowed")
     */
    public function edit(Pin $pin , Request $request , EntityManagerInterface $em):Response
    {

        $form = $this->createForm(PinType::class , $pin);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {


            $em->flush();
            $this->addFlash('success','pin modifier avec success');

            return $this->redirectToRoute('app_home');
        }
            return $this->render('pin/edit.html.twig', [
                'pin'=>$pin,
                'form' => $form->createView()
            ]);
        }
    /**
     * @Route("/pin/commentaire", name="app_pin_comm", methods={"GET", "POST"})
     *
     */
    public function new(ManagerRegistry $doctrine,Request $request, EntityManagerInterface $entityManager, UserRepository $userRepo , PinRepository $pinRepository): Response
    {

        $com = $request->request->get('com');


        $id = $request->request->get('id');
        $commentaire = new Comments();
        $commentaire->setContenu($com);
        $p = $doctrine->getRepository(Pin::class)->find($id);

        $commentaire->setUser($this->getUser());
        $commentaire->setPin($p);
        $entityManager->persist($commentaire);
        $entityManager->flush();

        return $this->redirectToRoute('app_pin_listecom', array('id' =>$id ));



    }


    /**
     * @Route("/pin/{id<[0-9]+>}/listcom", name="app_pin_listecom", methods={"GET", "POST"})
     *
     */
    public function listcom(ManagerRegistry $doctrine,Pin $pin , Request $request , EntityManagerInterface $entityManager , CommentsRepository $commentsRepository):Response
    {  $com = $request->request->get('com');
        $coms = $commentsRepository->findBy(['pin'=>$pin], ['createdAt' => 'DESC']);



        return $this->render('pin/listecom.html.twig', [
            'coms'=>$coms,
            'pin'=>$pin,

        ]);
    }


    /**
     * @Route("/pin/rechercher", name="app_pin_rechercher" ,methods={"GET","POST"})
     *
     */
    public function recherche(ManagerRegistry $doctrine,PinRepository $pinRepository  , Request $request  , EntityManagerInterface $em):Response
    {
        $re = $request->request->get('re');
        $ca = $request->request->get('ca');
        if ($re == "" && $ca != "") {
            $pin = $pinRepository->findBy(array('categorie' => $ca ,'audience'=>'Public'),['createdAt' => 'DESC']);


            return $this->render('pin/recherche.html.twig', [

                'pins' => $pin,

            ]);

        } else if ($re != "" && $ca == "") {
            /*test sur description et title*/
            $pin = $doctrine->getRepository(Pin::class)->findAllLIKEDESCRIPTION($re);
            return $this->render('pin/recherche.html.twig', [

                'pins' => $pin,

            ]);

        }
        else if ($re != "" && $ca != "") {
            /*test sur description et title et categorie*/
                        $pin = $doctrine->getRepository(Pin::class)->findAllby2($re,$ca);



            return $this->render('pin/recherche.html.twig', [

                'pins' => $pin,

            ]);

        }






        $pin = $pinRepository->findBy(array('audience'=>'Public'),['createdAt' => 'DESC']);


        return $this->render('pin/recherche.html.twig', [

            'pins' => $pin,

        ]);
    }
    /**
     * @Route("/{id}/delete", name="pin_delete", methods={"POST"})
     *
     */
    public function delete(Request $request, Pin $pin, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pin->getId(), $request->request->get('_token'))) {
        $entityManager->remove($pin);
        $entityManager->flush();
            $this->addFlash('info', 'Pin successfully deleted');
    }


        return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
    }

}

templates/pin/_delete.html.twig
<form method="post" action="{{ path('pin_delete', {'id': pin.id}) }}"
    onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pin.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pin/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form)}}
<div class="d-grid gap-2">
<input type="submit" value="{{ submitButtonText ?? 'Create Pin' }}"class="btn btn-primary " ></div>
{{ form_end(form) }}

templates/pin/create.html.twig
{% extends 'base.html.twig' %}

{% block title 'New pin' %}


{% block body %}
    <div class="row">
    <div class="col-md-6 mx-auto">
        <h1>create new pin</h1>
        {{ include('pin/_form.html.twig',{submitButtonText:'create'})}}

    </div></div>


{% endblock %}

templates/pin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title 'edit pin#' ~ pin.id %}


{% block body %}
<div class="row">
    <div class="col-md-6 mx-auto">
    <h1>edit pin{{ pin.id }}</h1>
    {{ include('pin/_form.html.twig',{submitButtonText:'Edit'})}}
    </div></div>
{% endblock %}

templates/pin/home.html.twig
{% extends 'base.html.twig' %}

{% block title 'Find all the best pins on earth!' %}

{% block body %}
    {% if pins|length > 0 %}
        <h1 class="mb-4 text-center text-muted">{{ pluralize(pins|length, 'Pin') }}</h1>

        {% for row in pins|batch(3) %}
            <div class="row mb-5">
                {% for pin in row %}
                    <div class="col-md-4">
                        <article class="pin bg-white rounded shadow">
                            <div class="mw-100 rounded-top overflow-hidden">
                                {% if is_granted('ROLE_USER') %}
                                <a href="{{ path('app_pin_listecom', {'id': pin.id}) }}">
                                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('public/uploads/pin/placeholder.jpg')) }}" alt="{{ pin.title }}" class="w-100" />                                </a>
                {% else %}
                    <a href="{{ path('app_pin_show', {'id': pin.id}) }}">
                        <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('public/uploads/pin/placeholder.jpg')) }}" alt="{{ pin.title }}" class="w-100" />                                </a>
                    {% endif %}
                            </div>
                            {% if is_granted('ROLE_USER') %}
                            <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_pin_listecom', {'id': pin.id}) }}" class="text-secondary text-decoration-none">{{ pin.title }}</a></h2>
                        {% else %}
                            <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_pin_show', {'id': pin.id}) }}" class="text-secondary text-decoration-none">{{ pin.title }}</a></h2>

                            {% endif %}
                            <p class="pl-3 pb-3 text-muted"><small>Submitted by {{ pin.user.fullName }}</small></p>
                        </article>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p class="mt-5 h1 text-center">No pins yet. <a href="{{ path('app_pin_create') }}">Be the first!</a></p>
    {% endif %}
{% endblock %}

templates/pin/listecom.html.twig
{% extends 'base.html.twig' %}
{% block title 'Find all the best pins on earth!' %}

{% block body %}




<!-- Main Body -->
<div class="container justify-content-center mt-100 mb-100" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-md-12">
            <div class="card"style="background-color: white">
                <div class="card-body" >
                    <div class="row">
<table>

                        <div class="col-md-6 ">
                            <div class="mw-100 rounded-top overflow-hidden">
                                <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('public/uploads/pin/placeholder.jpg' )) }}" alt="{{ pin.title }}" class="w-100" />
                                <p class="text-muted">
                                    <small>
                                        Submitted
                                        <time datetime="{{ pin.createdAt|date('Y-m-d H:i:s') }}">{{ pin.createdAt|ago }}</time>

                                    </small>
                                </p>
                                {% if  pin.user()==app.user %}
                                <div class="row">
                                    <div class="col-md-4">
                                        <a href="{{ path('app_pin_edit', {'id': pin.id}) }}" class="btn btn-light">Edit</a>

                                    </div>
                                    <div class="col-md-4">
                                        {{ include('pin/_delete.html.twig') }}
                                    </div>
                                    {% endif %}



                                    <br>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="p-3">

                                <h3   style="color: #B0413E " >{{ pin.title }} </h3>



                                <p class="pt-3 text-break">
                                    <label style="font-family: 'Imprint MT Shadow'">Description :</label>

                                    {{ pin.description }}
                                </p>





                                <form id="commentaire" action="{{ path('app_pin_comm') }}" method="post" >
                                    <div class="input-group">

                                        <textarea class="form-control" id="com" name="com"required aria-label="With textarea" placeholder="entre votre commentaire"></textarea>
                                        <div class="input-group-prepend">
                                            <input type="submit" name="commntaire" value="commentaire" class="btn btn-primary  ">
                                        </div>
                                    </div>

                                    <input type="hidden" id=id name="id" value="{{   pin.id }}">

                                </form>
                                <br>
                                {% if coms|length > 0 %}
                                <h4 class="card-title">Recent Comments</h4>
                                <h6 class="card-subtitle">Latest Comments section by users</h6>
                            </div>

                            {% for com in coms %}
                                <div class="comment-widgets m-b-20">
                                    <div class="d-flex flex-row comment-row">
                                        <div class="p-2"><span class="round"><img src="{{ app.user.gravatarUrl }}" alt="user" width="50"></span></div>
                                        <div class="comment-text w-100">
                                            <h5>{{ com.user.fullName }}</h5>
                                            <div class="comment-footer"> <span class="date"><time datetime="{{ com.createdAt|date('Y-m-d H:i:s') }}">{{ com.createdAt|ago }}</time></span> <span class="label label-info">Pending</span>  </div>
                                            <p class="m-b-5 m-t-10">{{ com.contenu }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            {% else %}
                                <p class="mt-5 h1 text-center">No comments yet. Be the first!</p>

                            {% endif %}
                        </div>
                    </div>
                </div></div></table>
                </div>
            </div>
        </div>
        <style>
            @import url(http://fonts.googleapis.com/css?family=Calibri:400,300,700);

            body {
                background-color: #d2d1d1;
                font-family: 'Calibri', sans-serif !important
            }

            .card-no-border .card {
                border: 0px;
                border-radius: 4px;
                -webkit-box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.05);
                box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.05)
            }

            .card-body {
                -ms-flex: 1 1 auto;
                flex: 1 1 auto;
                padding: 1.25rem
            }

            .comment-widgets .comment-row:hover {
                background: rgba(0, 0, 0, 0.02);
                cursor: pointer
            }

            .comment-widgets .comment-row {
                border-bottom: 1px solid rgba(120, 130, 140, 0.13);
                padding: 15px
            }

            .comment-text:hover {
                visibility: hidden
            }

            .comment-text:hover {
                visibility: visible
            }

            .label {
                padding: 3px 10px;
                line-height: 13px;
                color: #ffffff;
                font-weight: 400;
                border-radius: 4px;
                font-size: 75%
            }

            .round img {
                border-radius: 100%
            }

            .label-info {
                background-color: #1976d2
            }

            .label-success {
                background-color: green
            }

            .label-danger {
                background-color: #ef5350
            }

            .action-icons a {
                padding-left: 7px;
                vertical-align: middle;
                color: #99abb4
            }

            .action-icons a:hover {
                color: #1976d2
            }

            .mt-100 {
                margin-top: 100px
            }

            .mb-100 {
                margin-bottom: 100px
            }
        </style>

        {% endblock %}

templates/pin/my_pins.html.twig
{% extends 'base.html.twig' %}

{% block title 'Find all the best pins on earth!' %}

{% block body %}

    {% if pins|length > 0 %}
        <h1 class="mb-4 text-center text-muted"> ♥ {{ pluralize(pins|length, 'Pin') }}</h1>

        {% for row in pins|batch(3) %}
            <div class="row mb-5">
                {% for pin in row %}
                    <div class="col-md-4">
                        <article class="pin bg-white rounded shadow">
                            <div class="mw-100 rounded-top overflow-hidden">
                                <a href="{{ path('app_pin_listecom', {'id': pin.id}) }}">
                                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('public/uploads/pin/placeholder.jpg')) }}" alt="{{ pin.title }}" class="w-100" />                                </a>
                            </div>
                            <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_pin_listecom', {'id': pin.id}) }}" class="text-secondary text-decoration-none">{{ pin.title }}</a></h2>
                            <p class="pl-3 pb-3 text-muted"><small>Submitted by {{ pin.user.fullName }}</small></p>
                        </article>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p class="mt-5 h1 text-center">No pins yet. <a href="{{ path('app_pin_create') }}">Be the first!</a></p>
    {% endif %}
{% endblock %}

templates/pin/recherche.html.twig
{% extends 'base.html.twig' %}

{% block title 'Find all the best pins on earth!' %}

{% block body %}
    {% if pins|length > 0 %}
        <h1 class="mb-4 text-center text-muted">{{ pluralize(pins|length, 'Pin') }}</h1>

        {% for row in pins|batch(3) %}
            <div class="row mb-5">
                {% for pin in row %}
                    <div class="col-md-4">
                        <article class="pin bg-white rounded shadow">
                            <div class="mw-100 rounded-top overflow-hidden">
                                <a href="{{ path('app_pin_show', {id: pin.id}) }}">
                                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('public/uploads/pin/placeholder.jpg'))  }}" alt="{{ pin.title }}" class="w-100" />                                </a>
                            </div>
                            <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_pin_show', {id: pin.id}) }}" class="text-secondary text-decoration-none">{{ pin.title }}</a></h2>
                            <p class="pl-3 pb-3 text-muted"><small>Submitted by {{ pin.user.fullName }}</small></p>
                        </article>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p class="mt-5 h1 text-center">No pins yet. <a href="{{ path('app_pin_create') }}">Be the first!</a></p>
    {% endif %}
{% endblock %}

templates/pin/show.html.twig
{% extends 'base.html.twig' %}

{% block title pin.title %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <article class="pin bg-white rounded shadow">
                <div class="mw-100 rounded-top overflow-hidden">
                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('public/uploads/pin/placeholder.jpg'))  }}" alt="{{ pin.title }}" class="w-100" />
                </div>

                <div class="p-3">
                    <h1 class="h5 text-secondary">{{ pin.title }}</h1>

                    <p class="text-muted">
                        <small>
                            Submitted
                            <time datetime="{{ pin.createdAt|date('Y-m-d H:i:s') }}">{{ pin.createdAt|ago }}</time>
                            by {{ pin.user.fullName }}
                        </small>
                    </p>

                    <p class="pt-3 text-break">
                        {{ pin.description }}
                    </p>


                </div>
            </article>
        </div>
    </div>
{% endblock %}